# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1395, 884)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1395, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenPointCloud = QtWidgets.QAction(MainWindow)
        self.actionOpenPointCloud.setObjectName("actionOpenPointCloud")
        self.actionRecentFiles = QtWidgets.QAction(MainWindow)
        self.actionRecentFiles.setObjectName("actionRecentFiles")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.import_video = QtWidgets.QAction(MainWindow)
        self.import_video.setObjectName("import_video")
        self.import_images = QtWidgets.QAction(MainWindow)
        self.import_images.setObjectName("import_images")
        self.menu.addAction(self.actionOpenPointCloud)
        self.menu.addAction(self.actionRecentFiles)
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.import_video)
        self.menu_2.addAction(self.import_images)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "导入"))
        self.actionOpenPointCloud.setText(_translate("MainWindow", "打开点云"))
        self.actionRecentFiles.setText(_translate("MainWindow", "最近文件"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))
        self.import_video.setText(_translate("MainWindow", "导入视频"))
        self.import_images.setText(_translate("MainWindow", "导入图像文件夹"))
